import vtk
import time
import cv2 as cv
reader1 = vtk. vtkSTLReader()
reader1. SetFileName("clock_0.stl")
reader2 = vtk. vtkSTLReader()
reader2. SetFileName("clock_1.stl")
reader3 = vtk. vtkSTLReader()
reader3. SetFileName("clock_2.stl")
mapper1 = vtk.vtkPolyDataMapper()
mapper1.SetInputConnection(reader1.GetOutputPort())
mapper2 = vtk.vtkPolyDataMapper()
mapper2.SetInputConnection(reader2.GetOutputPort())
mapper3 = vtk.vtkPolyDataMapper()
mapper3.SetInputConnection(reader3.GetOutputPort())
actor1 = vtk.vtkActor()
actor1.SetMapper(mapper1)
actor2 = vtk.vtkActor()
actor2.SetMapper(mapper2)
actor3 = vtk.vtkActor()
actor3.SetMapper(mapper3)
renderer = vtk.vtkRenderer()
renderWindow = vtk.vtkRenderWindow()
renderWindow.AddRenderer(renderer)
renderWindowInteractor = vtk.vtkRenderWindowInteractor()
renderWindowInteractor.SetRenderWindow(renderWindow)
renderer.AddActor(actor1)
renderer.AddActor(actor2)
renderer.AddActor(actor3)
print("actor1center:",actor1.GetCenter())
print("actor2center:",actor2.GetCenter())
print("actor3center:",actor3.GetCenter())
renderer.SetBackground(0,0,0.8)
actor1.SetOrigin(actor1.GetCenter())
actor2.SetOrigin(actor1.GetCenter())
actor3.SetOrigin(actor1.GetCenter())
actor1.GetProperty().SetColor(1, 0, 0)
actor2.GetProperty().SetColor(1, 1, 0)
actor3.GetProperty().SetColor(1, 1, 1)
for i in range(60):
    actor2.RotateZ(-6)
    actor3.RotateZ(-0.1)    
    time.sleep(1)
    renderWindow.Render()


